export const ABI = {
  address: "0x9ea9300f026b774afd2bc3054707615e71ac4883c9f4bffa3613f7e308da824b",
  name: "market",
  friends: [],
  exposed_functions: [
    {
      name: "claim_winnings",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "create_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::string::String",
        "u64",
        "0x1::object::Object<0x1::fungible_asset::Metadata>",
      ],
      return: [],
    },
    {
      name: "enter_position",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "bool", "u64"],
      return: [],
    },
    {
      name: "get_market_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: [
        "0x9ea9300f026b774afd2bc3054707615e71ac4883c9f4bffa3613f7e308da824b::market::MarketView",
      ],
    },
    {
      name: "get_player_position_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: [
        "0x9ea9300f026b774afd2bc3054707615e71ac4883c9f4bffa3613f7e308da824b::market::PositionView",
      ],
    },
    {
      name: "settle_market",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "bool"],
      return: [],
    },
  ],
  structs: [
    {
      name: "Position",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "player_address", type: "address" },
        { name: "direction", type: "bool" },
        { name: "stake_amount", type: "u64" },
        { name: "effective_stake", type: "u64" },
      ],
    },
    {
      name: "Market",
      is_native: false,
      is_event: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        { name: "id", type: "address" },
        { name: "description", type: "0x1::string::String" },
        { name: "treasury", type: "address" },
        { name: "winning_side", type: "0x1::option::Option<bool>" },
        { name: "create_time", type: "u64" },
        { name: "close_time", type: "u64" },
        {
          name: "a_pool",
          type: "0x1::object::Object<0x1::fungible_asset::FungibleStore>",
        },
        {
          name: "b_pool",
          type: "0x1::object::Object<0x1::fungible_asset::FungibleStore>",
        },
        { name: "total_a_effective_stake", type: "u64" },
        { name: "total_b_effective_stake", type: "u64" },
        {
          name: "positions",
          type: "0x1::smart_table::SmartTable<address, 0x9ea9300f026b774afd2bc3054707615e71ac4883c9f4bffa3613f7e308da824b::market::Position>",
        },
        { name: "status", type: "bool" },
      ],
    },
    {
      name: "MarketHolder",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        { name: "signer_cap", type: "0x1::account::SignerCapability" },
        {
          name: "markets",
          type: "0x1::smart_table::SmartTable<address, 0x9ea9300f026b774afd2bc3054707615e71ac4883c9f4bffa3613f7e308da824b::market::Market>",
        },
      ],
    },
    {
      name: "MarketView",
      is_native: false,
      is_event: true,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "id", type: "address" },
        { name: "description", type: "0x1::string::String" },
        { name: "treasury", type: "address" },
        { name: "winning_side", type: "0x1::option::Option<bool>" },
        { name: "create_time", type: "u64" },
        { name: "close_time", type: "u64" },
        {
          name: "a_pool",
          type: "0x1::object::Object<0x1::fungible_asset::FungibleStore>",
        },
        {
          name: "b_pool",
          type: "0x1::object::Object<0x1::fungible_asset::FungibleStore>",
        },
        { name: "total_a_effective_stake", type: "u64" },
        { name: "total_b_effective_stake", type: "u64" },
        { name: "status", type: "bool" },
      ],
    },
    {
      name: "PositionView",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        { name: "direction", type: "bool" },
        { name: "stake_amount", type: "u64" },
        { name: "effective_stake", type: "u64" },
      ],
    },
  ],
} as const;
